// src/components/TodoApp.jsx
import React, { useState } from 'react';

function TodoApp() {
  const [todos, setTodos] = useState([
    { id: 1, text: 'Learn React.js', done: false },
    { id: 2, text: 'Build a React app', done: false },
    { id: 3, text: 'Master React', done: false }
  ]);
  const [newTodoText, setNewTodoText] = useState('');

  const addTodo = () => {
    if (newTodoText.trim() !== '') {
      setTodos([
        ...todos,
        { id: todos.length + 1, text: newTodoText, done: false }
      ]);
      setNewTodoText('');
    }
  };

  const removeTodo = (todoId) => {
    setTodos(todos.filter(todo => todo.id !== todoId));
  };

  const toggleTodoDone = (todoId) => {
    setTodos(todos.map(todo => 
      todo.id === todoId ? { ...todo, done: !todo.done } : todo
    ));
  };

  return (
    <div id="app">
      {todos.map(todo => (
        <div className="todo-item" key={todo.id}>
          <input
            type="checkbox"
            checked={todo.done}
            onChange={() => toggleTodoDone(todo.id)}
            className="todo-checkbox"
          />
          <span className="todo-text">{todo.text}</span>
          <span className="todo-delete" onClick={() => removeTodo(todo.id)}>X</span>
        </div>
      ))}
      <div className="add-todo">
        <input
          type="text"
          value={newTodoText}
          onChange={(e) => setNewTodoText(e.target.value)}
          placeholder="Add new todo"
        />
        <button onClick={addTodo}>Add</button>
      </div>
    </div>
  );
}

export default TodoApp;

// src/components/TodoApp.vue
<template>
  <div id="app">
    <div class="todo-item" v-for="todo in todos" :key="todo.id">
      <input type="checkbox" v-model="todo.done" class="todo-checkbox">
      <span class="todo-text">{{ todo.text }}</span>
      <span class="todo-delete" @click="removeTodo(todo.id)">X</span>
    </div>
    <div class="add-todo">
      <input type="text" v-model="newTodoText" placeholder="Add new todo">
      <button @click="addTodo">Add</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TodoApp',
  data() {
    return {
      newTodoText: '',
      todos: [
        { id: 1, text: 'Learn Vue.js', done: false },
        { id: 2, text: 'Build a Vue app', done: false },
        { id: 3, text: 'Master Vue', done: false }
      ],
      nextTodoId: 4
    }
  },
  methods: {
    addTodo() {
      if (this.newTodoText.trim() !== '') {
        this.todos.push({
          id: this.nextTodoId++,
          text: this.newTodoText,
          done: false
        });
        this.newTodoText = '';
      }
    },
    removeTodo(todoId) {
      this.todos = this.todos.filter(todo => todo.id !== todoId);
    },
    toggleTodoDone(todoId) {
      const todo = this.todos.find(todo => todo.id === todoId);
      if (todo) {
        todo.done = !todo.done;
      }
    }
  }
}
</script>

<style scoped>
/* Basic styling for the to-do list application */
body {
  font-family: Arial, sans-serif;
  background-color: #f5f5f5;
  margin: 0;
  padding: 20px;
}

#app {
  max-width: 600px;
  margin: 0 auto;
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

.todo-item {
  display: flex;
  align-items: center;
  padding: 10px 0;
}

.todo-item:not(:last-child) {
  border-bottom: 1px solid #eee;
}

.todo-checkbox {
  margin-right: 15px;
}

.todo-text {
  flex: 1;
}

.todo-delete {
  color: #888;
  cursor: pointer;
}

.todo-delete:hover {
  color: #f00;
}

.add-todo {
  display: flex;
  margin-top: 20px;
}

.add-todo input[type="text"] {
  flex: 1;
  padding: 10px;
  margin-right: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.add-todo button {
  padding: 10px 20px;
  background-color: #5cb85c;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.add-todo button:hover {
  background-color: #449d44;
}
</style>
